### ISSUE TITLE
Cross Compile Error

### ISSUE THREAD

**Issue by lsdy** [google/glog#358]
When I compile with arm-gcc 4.4,I add tag "-std=c++0x".
```
In file included from /home/eclipse-workspace/Push/src/base/Logging.h:17,
                 from Push.cpp:12:
/home/eclipse-workspace/Push/src/log/glog/logging.h: In function 'T google::CheckNotNull(const char*, int, const char*, T&&)':
/home/eclipse-workspace/Push/src/log/glog/logging.h:1333: error: 'nullptr' was not declared in this scope
```
__GXX_EXPERIMENTAL_CXX0X__ is defined while the gcc version is smaller than 4.7

**Comment by PolynomialDivision** [comment]
Similar issue when I try to cross compile to mips_24kc with OpenWrt Imagebuilder:

```
src/symbolize_unittest.cc: In function 'int main(int, char**)':
src/symbolize_unittest.cc:410:3: error: 'TestWithPCInsideInlineFunction' was not declared in this scope
   TestWithPCInsideInlineFunction();
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/symbolize_unittest.cc:411:3: error: 'TestWithPCInsideNonInlineFunction' was not declared in this scope
   TestWithPCInsideNonInlineFunction();
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/symbolize_unittest.cc:412:3: error: 'TestWithReturnAddress' was not declared in this scope
   TestWithReturnAddress();
   ^~~~~~~~~~~~~~~~~~~~~
```

Similar to
- https://github.com/google/glog/issues/207
- https://github.com/google/glog/issues/104

glog: v0.4.0
gflags: v2.2.2

**Comment by edwardzjl** [comment]
> Similar issue when I try to cross compile to mips_24kc with OpenWrt Imagebuilder:
> 
> ```
> src/symbolize_unittest.cc: In function 'int main(int, char**)':
> src/symbolize_unittest.cc:410:3: error: 'TestWithPCInsideInlineFunction' was not declared in this scope
>    TestWithPCInsideInlineFunction();
>    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> src/symbolize_unittest.cc:411:3: error: 'TestWithPCInsideNonInlineFunction' was not declared in this scope
>    TestWithPCInsideNonInlineFunction();
>    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> src/symbolize_unittest.cc:412:3: error: 'TestWithReturnAddress' was not declared in this scope
>    TestWithReturnAddress();
>    ^~~~~~~~~~~~~~~~~~~~~
> ```
> 
> Similar to
> 
> * #207
> * #104
> 
> glog: v0.4.0
> gflags: v2.2.2

Same problem, have you solved it?

**Comment by edwardzjl** [comment]
I solved this issue by
1. reinstall gflag with -DBUILD_SHARED_LIBS=ON
2. do not use ./autogen.sh && ./configure to generate Makefile, instead use cmake
