### ISSUE TITLE
does not build with Bazel 0.10.0 and gcc 7.2.0

### ISSUE THREAD

**Issue by andreykulik** [google/glog#297]
external/com_google_glog/src/utilities.h:146:1: error: '_START_GOOGLE_NAMESPACE_' does not name a type; did you mean 'GOOGLE_NAMESPACE'?
 _START_GOOGLE_NAMESPACE_
 ^~~~~~~~~~~~~~~~~~~~~~~~
 GOOGLE_NAMESPACE
external/com_google_glog/src/utilities.h:234:1: error: '_END_GOOGLE_NAMESPACE_' does not name a type; did you mean 'GOOGLE_NAMESPACE'?
 _END_GOOGLE_NAMESPACE_
 ^~~~~~~~~~~~~~~~~~~~~~

**Comment by andreykulik** [comment]
--output from bazel verbose:

/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/external/com_google_glog/_objs/glog/external/com_google_glog/src/raw_logging.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/external/com_google_glog/_objs/glog/external/com_google_glog/src/raw_logging.pic.o' -fPIC -iquote external/com_google_glog -iquote bazel-out/k8-fastbuild/genfiles/external/com_google_glog -iquote external/com_github_gflags_gflags -iquote bazel-out/k8-fastbuild/genfiles/external/com_github_gflags_gflags -iquote external/bazel_tools -iquote bazel-out/k8-fastbuild/genfiles/external/bazel_tools -Ibazel-out/k8-fastbuild/bin/external/com_google_glog/_virtual_includes/glog -isystem external/com_github_gflags_gflags/include -isystem bazel-out/k8-fastbuild/genfiles/external/com_github_gflags_gflags/include -isystem external/bazel_tools/tools/cpp/gcc3 -Wno-sign-compare -Wno-unused-function -Wno-unused-local-typedefs -Wno-unused-variable -DGLOG_BAZEL_BUILD '-DGOOGLE_NAMESPACE=google' -DHAVE_PTHREAD -DHAVE_SYS_UTSNAME_H -DHAVE_SYS_SYSCALL_H -DHAVE_SYS_TIME_H -DHAVE_STDINT_H -DHAVE_STRING_H -DHAVE_SIGACTION -DHAVE_PREAD -Ibazel-out/k8-fastbuild/genfiles/external/com_google_glog/glog_internal -DHAVE_LIB_GFLAGS -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_glog/src/raw_logging.cc -o bazel-out/k8-fastbuild/bin/external/com_google_glog/_objs/glog/external/com_google_glog/src/raw_logging.pic.o)

**Comment by andreykulik** [comment]
I found a workaround it, but this looks ugly: https://github.com/antonovvk/bazel_glog/blob/master/glog.BUILD 
Since START_GOOGLE_NAMESPACE always resolves to namespace google { you don't need that magic anymore?

**Comment by drigz** [comment]
@andreykulik Could you post your WORKSPACE file? It's possible you have an incompatible version of gflags which is leaking config.h - you should try using the same version as specified in [glog's WORKSPACE](https://github.com/google/glog/blob/4c4631c9b3d20722fc11b18ca1d7a58fced99ef9/WORKSPACE).

If that doesn't help, posting your WORKSPACE file should help reproduce the issue. Additionally, could you rerun this modified build command, which will output the results of preprocessing to ~/raw_logging.preprocessed.cc, and upload that file?

```
cd <path from output of `bazel build -s`> && \
/usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/k8-fastbuild/bin/external/com_google_glog/_objs/glog/external/com_google_glog/src/raw_logging.pic.d '-frandom-seed=bazel-out/k8-fastbuild/bin/external/com_google_glog/_objs/glog/external/com_google_glog/src/raw_logging.pic.o' -fPIC -iquote external/com_google_glog -iquote bazel-out/k8-fastbuild/genfiles/external/com_google_glog -iquote external/com_github_gflags_gflags -iquote bazel-out/k8-fastbuild/genfiles/external/com_github_gflags_gflags -iquote external/bazel_tools -iquote bazel-out/k8-fastbuild/genfiles/external/bazel_tools -Ibazel-out/k8-fastbuild/bin/external/com_google_glog/_virtual_includes/glog -isystem external/com_github_gflags_gflags/include -isystem bazel-out/k8-fastbuild/genfiles/external/com_github_gflags_gflags/include -isystem external/bazel_tools/tools/cpp/gcc3 -Wno-sign-compare -Wno-unused-function -Wno-unused-local-typedefs -Wno-unused-variable -DGLOG_BAZEL_BUILD '-DGOOGLE_NAMESPACE=google' -DHAVE_PTHREAD -DHAVE_SYS_UTSNAME_H -DHAVE_SYS_SYSCALL_H -DHAVE_SYS_TIME_H -DHAVE_STDINT_H -DHAVE_STRING_H -DHAVE_SIGACTION -DHAVE_PREAD -Ibazel-out/k8-fastbuild/genfiles/external/com_google_glog/glog_internal -DHAVE_LIB_GFLAGS -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -E external/com_google_glog/src/raw_logging.cc -o ~/raw_logging.preprocessed.cc
```

**Comment by andreykulik** [comment]
[env.zip](https://github.com/google/glog/files/1725429/env.zip)
Thank you, @drigz. 

I attached my workspace and raw_logging files. 
I build only core glog dependency, so, it should not be affected by wrong gflags, right?

bazel build -s @com_google_glog//:glog --verbose_failures

**Comment by andreykulik** [comment]
When I explicitly added gflags http archive to my workspace in the first position, it builds. Hm. Thus, wrong gflag dependency leaks somewhere.

**Comment by drigz** [comment]
@com_google_glog//:glog depends on gflags and will fail to build without it. However, grpc_deps() was adding an older version of gflags to the workspace. Putting the correct version at the top of the file makes grpc_deps() use the that version.

I've sent this pull request which may avoid others having the same issue: https://github.com/grpc/grpc/pull/14435

**Comment by andreykulik** [comment]
Thank you! I guess this is fixed by now?
