### ISSUE TITLE
MSVC 2013 build has been broken

### ISSUE THREAD

**Issue by mmp** [google/glog#213]
Building TOT with MSVC2013 gives the error:

```
(ClCompile target) -> 
  C:\pbrt-v3\src\ext\glog\src\logging.cc(1154): error C2483: 'thread_msg_data' : object with constructor or destructor cannot be declared 'thread' [c:\pbrt-v3\build\src\ext\glog\glog.vcxproj]
```

It looks like this is due to the changes introduced in 2df0ca34aa3000dadf76633ca700abf0bf50756d.

**Comment by jasminezz** [comment]
@mmp I have the same error ,building with VS2013. Have you solved it ?

**Comment by mmp** [comment]
I haven't spent any time working on a work-around/fix.

**Comment by siniyake** [comment]
I am stuck in this problem too. Has anyone solved it so far?

**Comment by shinh** [comment]
Could someone test if this works?

https://github.com/google/glog/pull/217

**Comment by tangketan** [comment]
It seems just changing thread_msg_data to pointer type is enough, no need to change the CMakeLists.txt.

**Comment by sergiud** [comment]
Please test PR #226.

**Comment by sergiud** [comment]
Fixed in 2fe6508e536032b321067a541b6f0a3a54089bc3.
