### PR TITLE
release 0.5

### LINKED ISSUE #505: glog cmake support in upstream packages
Since latest `v0.4.0` release glog cmake installation creates a `glogConfig.cmake` on installation. Unfortunately upstream packages don't yet use the cmake configuration (currently autoconfig is used) and thus no `glogConfig.cmake` files get generated and installed to 

Some Upstream bugs I've found:
- [ ] [Arch Linux Tasks](https://bugs.archlinux.org/task/55185)
- [ ] [Ubuntu Launchpad Bug](https://bugs.launchpad.net/ubuntu/+source/google-glog/+bug/1815110)

This leads to downstream projects needing to provide `FindGlog.cmake` files
https://github.com/ceres-solver/ceres-solver/issues/535

One show stopper I can think of is the lack of a generated pkgconfig file in `v0.4.0` of glog. In current `master` branch this file is already created. So please make a new release (for example `v0.4.1`) which adds the pkgconfig file creation to the cmake configuration. I don't think maintainer would update a package to cmake just to loose functionality

### LINKED ISSUE #617: When will the new version be released?
When will the new version be released?

with timestamp_in_logfile_name features

### PR DESCRIPTION
**Pull request by sergiud**
Closes #617
Closes #505 

[Full Changelog](https://github.com/google/glog/compare/v0.4.0...HEAD)

**Implemented enhancements:**

- Add support for customizing the prefix format [\#578](https://github.com/google/glog/issues/578)
- "sprintf" function being used in googletest.h which is not secure [\#536](https://github.com/google/glog/issues/536)
- stacktrace is not produced on aarch64 [\#531](https://github.com/google/glog/issues/531)
- Documenting minimum C++ version [\#527](https://github.com/google/glog/issues/527)
- Glog file separation by year [\#516](https://github.com/google/glog/issues/516)
- Bazel support for windows [\#472](https://github.com/google/glog/issues/472)
- GOOGLE\_GLOG\_DLL\_DECL needs to be put into header file [\#469](https://github.com/google/glog/issues/469)
- Glog should delete old log files automaticly [\#423](https://github.com/google/glog/issues/423)
- CHECK\_XX variants do not compile if nullptr is an argument [\#341](https://github.com/google/glog/issues/341)
- autogen.sh makes git directory dirty [\#308](https://github.com/google/glog/issues/308)
- LogSink::ToString has no microsecond precision. [\#307](https://github.com/google/glog/issues/307)
- Conan package for glog [\#262](https://github.com/google/glog/issues/262)
- How to change format of logger? for example time and verbose level name and etc [\#229](https://github.com/google/glog/issues/229)
- Username lookup needs a tuneup [\#211](https://github.com/google/glog/issues/211)
- Feature request for sudo make uninstall [\#163](https://github.com/google/glog/issues/163)
- glog should use ThreadSanitizer \(TSAN\) dynamic annotations [\#80](https://github.com/google/glog/issues/80)
- Add support for deleting old logs [\#36](https://github.com/google/glog/issues/36)
- CHECK support for nullptr \(fixes \#341\) [\#641](https://github.com/google/glog/pull/641) ([sergiud](https://github.com/sergiud))
- cmake: do not require a C compiler [\#627](https://github.com/google/glog/pull/627) ([sergiud](https://github.com/sergiud))
- use C++ headers [\#626](https://github.com/google/glog/pull/626) ([sergiud](https://github.com/sergiud))
- removed windows-specific headers [\#625](https://github.com/google/glog/pull/625) ([sergiud](https://github.com/sergiud))
- document C++ version [\#623](https://github.com/google/glog/pull/623) ([sergiud](https://github.com/sergiud))
- Add support for customizing the prefix format [\#554](https://github.com/google/glog/pull/554) ([santigl](https://github.com/santigl))
- Add extra information in log file header \(application build/version, actual duration time\) [\#438](https://github.com/google/glog/pull/438) ([d-uspenskiy](https://github.com/d-uspenskiy))
- Use libunwind as an imported target [\#368](https://github.com/google/glog/pull/368) ([UVV-gh](https://github.com/UVV-gh))
- Annotate LOG\_EVERY\_N macros as a benign race for TSAN [\#263](https://github.com/google/glog/pull/263) ([kennyyu](https://github.com/kennyyu))

**Fixed bugs:**

- Incorrect Unwind version parser [\#598](https://github.com/google/glog/issues/598)
- Large integers get truncated [\#594](https://github.com/google/glog/issues/594)
- Windows shared library generates linkage warnings [\#569](https://github.com/google/glog/issues/569)
- Replace obsolete \_\_CYGWIN64\_\_ macro [\#566](https://github.com/google/glog/issues/566)
- Disabling 'Symbolize functionality' is not working [\#563](https://github.com/google/glog/issues/563)
- LOG\_TO\_STRING and std namespace [\#550](https://github.com/google/glog/issues/550)
- Ownership with SetLogger [\#524](https://github.com/google/glog/issues/524)
- gtest usage not implemented in CMake build system [\#510](https://github.com/google/glog/issues/510)
- ac\_cv\_\_\_attribute\_\_\_printf\_4\_5 not set in CMake build system [\#509](https://github.com/google/glog/issues/509)
- --max\_log\_size not work when larger than 4096 [\#497](https://github.com/google/glog/issues/497)
- vmodule flag is not declared [\#466](https://github.com/google/glog/issues/466)
- TSan warning: a race in LOG\_EVERY\_N and friends [\#439](https://github.com/google/glog/issues/439)
- stacktrace unittest hangs on MSVC [\#328](https://github.com/google/glog/issues/328)
- EXC\_BAD\_ACCESS on iOS [\#275](https://github.com/google/glog/issues/275)
- Signal handler tests fail on ARM [\#256](https://github.com/google/glog/issues/256)
- glog 0.3.5 compilation failed on Centos 7 [\#243](https://github.com/google/glog/issues/243)
- ./libtool: line 6000: cd: no/lib: No such file or directory [\#215](https://github.com/google/glog/issues/215)
- Test stl\_logging fails in macOS CMake build [\#201](https://github.com/google/glog/issues/201)
- autoconf build does not version the library [\#196](https://github.com/google/glog/issues/196)
- gcc 4.7.2, 4.8.3, 4.9.2 unit test failures on C++11 [\#14](https://github.com/google/glog/issues/14)
- fix gflags windows linker warnings [\#640](https://github.com/google/glog/pull/640) ([sergiud](https://github.com/sergiud))
- fixed windows builds [\#639](https://github.com/google/glog/pull/639) ([sergiud](https://github.com/sergiud))
- fix LogCleaner::IsLogFromCurrentProject for filename\_extension [\#637](https://github.com/google/glog/pull/637) ([xiaobfly](https://github.com/xiaobfly))
- fully qualify std::string [\#624](https://github.com/google/glog/pull/624) ([sergiud](https://github.com/sergiud))
- handle --max\_log\_size overflow [\#622](https://github.com/google/glog/pull/622) ([sergiud](https://github.com/sergiud))
- cmake: optionally use gtest [\#621](https://github.com/google/glog/pull/621) ([sergiud](https://github.com/sergiud))
- cmake: allow to disable symbolize [\#620](https://github.com/google/glog/pull/620) ([sergiud](https://github.com/sergiud))
- build: set ac\_cv\_\_\_attribute\_\_\_printf\_4\_5 [\#618](https://github.com/google/glog/pull/618) ([sergiud](https://github.com/sergiud))
- cmake: fixed unwind patch component match check [\#613](https://github.com/google/glog/pull/613) ([sergiud](https://github.com/sergiud))

**Closed issues:**

- call InitGoogleLogging get a segment fault [\#607](https://github.com/google/glog/issues/607)
- BUILD file will create a conflict with build/ folder [\#606](https://github.com/google/glog/issues/606)
- glog don't create log file in visual c++ dll project [\#605](https://github.com/google/glog/issues/605)
- error in CMAKE installation steps--$ git clone git@github.com:google/glog.git should change to $ git clone https://github.com/google/glog.git [\#603](https://github.com/google/glog/issues/603)
- No system link created along with the log files [\#599](https://github.com/google/glog/issues/599)
- CMake build instructions do not work for paths with ampersand [\#597](https://github.com/google/glog/issues/597)
- publicly visible Bazel target no longer provides any headers [\#596](https://github.com/google/glog/issues/596)
- LogCleaner::IsLogFromCurrentProject incorrect when SetLogFilenameExtension [\#589](https://github.com/google/glog/issues/589)
- EnableLogCleaner not recognized [\#586](https://github.com/google/glog/issues/586)
- IsGlogLog problem [\#584](https://github.com/google/glog/issues/584)
- Build fails with clang-cl due to undefined symbols [\#575](https://github.com/google/glog/issues/575)
- Write the correct Windows version in the log header [\#572](https://github.com/google/glog/issues/572)
- Ability to write time in UTC in log files [\#571](https://github.com/google/glog/issues/571)
- compile error: use of overloaded operator '\<\<' is ambiguous [\#562](https://github.com/google/glog/issues/562)
- glog error log was incorrrectly written to unexpected memory [\#561](https://github.com/google/glog/issues/561)
- How to disable logging. [\#556](https://github.com/google/glog/issues/556)
- Cannot compile  "configure: WARNING: 'missing' script is too old or missing" [\#544](https://github.com/google/glog/issues/544)
- Support to modify verbose log level for mudules [\#538](https://github.com/google/glog/issues/538)
- Dropping autoconf support [\#537](https://github.com/google/glog/issues/537)
- Failed to print INFO and WARNING log [\#533](https://github.com/google/glog/issues/533)
- glog rpm installation fails if openstack-train repo is enabled [\#522](https://github.com/google/glog/issues/522)
- stripped binaries produce useless backtraces [\#514](https://github.com/google/glog/issues/514)
- Flag --incompatible\_no\_implicit\_file\_export will break Google Logging in a future Bazel release [\#512](https://github.com/google/glog/issues/512)
- Flag --incompatible\_load\_cc\_rules\_from\_bzl will break Google Logging in Bazel 1.2.1 [\#507](https://github.com/google/glog/issues/507)
- Flag --incompatible\_no\_implicit\_file\_export will break Google Logging in Bazel 1.2.1 [\#506](https://github.com/google/glog/issues/506)
- Is there any way logging without a mutex [\#504](https://github.com/google/glog/issues/504)
- Including glog/logging.h triggers -Wunused-parameter on g++ [\#493](https://github.com/google/glog/issues/493)
- Bazel: building glog with custom version gflags [\#480](https://github.com/google/glog/issues/480)
- max\_log\_size flag does not work on AIX or linux [\#476](https://github.com/google/glog/issues/476)
- cmake/DetermineGflagsNamespace.cmake was ignored when repush [\#473](https://github.com/google/glog/issues/473)
- Conflict with gflags [\#458](https://github.com/google/glog/issues/458)
- log file name error after application restart [\#457](https://github.com/google/glog/issues/457)
- App security test reports Insecure API for React Native iOS App - Binary Analysis \(IPA\) [\#453](https://github.com/google/glog/issues/453)
- multi thread cant share glog setting [\#450](https://github.com/google/glog/issues/450)
- How do I write logs to files only? [\#436](https://github.com/google/glog/issues/436)
- Crash in symbolize\_unittest on Ubuntu 18.04 x86\_64 [\#435](https://github.com/google/glog/issues/435)
- Does glog support compress log files? [\#434](https://github.com/google/glog/issues/434)
- Bazel build doesn't set correct compile flags. [\#430](https://github.com/google/glog/issues/430)
- how to change the name of final dynamic library [\#427](https://github.com/google/glog/issues/427)
- suggest about gflags [\#426](https://github.com/google/glog/issues/426)
- about filename\_extension\_ in CreateLogfile [\#395](https://github.com/google/glog/issues/395)
- Add cc\_library for ScopedMockLog [\#392](https://github.com/google/glog/issues/392)
- When building a react native project glog is causing a failure. [\#382](https://github.com/google/glog/issues/382)
- glog's endline is not thread safe when using with another logging system?! [\#379](https://github.com/google/glog/issues/379)
- Logfile full within 1s results in error [\#378](https://github.com/google/glog/issues/378)
- InitGoogleLogging bug ，Could not create logging file [\#375](https://github.com/google/glog/issues/375)
- golang/glog sometime can not create the log\_dir? [\#369](https://github.com/google/glog/issues/369)
- static google::log\_mutex destroyed on exit, while other still existing threads want to log [\#363](https://github.com/google/glog/issues/363)
- Does GLOG support log logs by day? [\#362](https://github.com/google/glog/issues/362)
- how to compile it for android ndk? [\#360](https://github.com/google/glog/issues/360)
- Cross Compile Error [\#358](https://github.com/google/glog/issues/358)
- add daemon\(1,0\)  ,then log is missing  [\#357](https://github.com/google/glog/issues/357)
- logtostderr filtering [\#356](https://github.com/google/glog/issues/356)
- Get trouble in compiling glog for android! [\#355](https://github.com/google/glog/issues/355)
- stl\_logging unit test don't pass [\#348](https://github.com/google/glog/issues/348)
- Stacktrace is not printed by failure signal handler when built with Bazel [\#346](https://github.com/google/glog/issues/346)
- When might 0.3.6 be released? [\#345](https://github.com/google/glog/issues/345)
- Unittest generates warning with C++17 regarding auto\_ptr [\#335](https://github.com/google/glog/issues/335)
- Use Upstream GoogleTest [\#333](https://github.com/google/glog/issues/333)
- Static declaration of 'pread' follows non-static declaration error while building in xcode [\#326](https://github.com/google/glog/issues/326)
- \_\_declspec\(dllimport\) public: \_\_thiscall google::base::CheckOpMessageBuilder::CheckOpMessageBuilder\(char const \*\) [\#316](https://github.com/google/glog/issues/316)
- glog can't be compiled using Android NDK r16 [\#306](https://github.com/google/glog/issues/306)
- libunwind GetStackTrace implementation doesn't allow concurrent invocations [\#298](https://github.com/google/glog/issues/298)
- VLOG before InitGoogleLogging causes crash [\#290](https://github.com/google/glog/issues/290)
- macro 'AM\_CONFIG\_HEADER' not found in library [\#271](https://github.com/google/glog/issues/271)
- Print binary-identifying info at the top of each file [\#269](https://github.com/google/glog/issues/269)
- The spec.prepare\_command lead an error [\#255](https://github.com/google/glog/issues/255)
- signalhandler\_unittest tests fails on aarch64 [\#219](https://github.com/google/glog/issues/219)
- Compiling error: undefined references to `google::base::CheckOpMessageBuilder::NewString\[abi:cxx11\]\(\) [\#195](https://github.com/google/glog/issues/195)
- \[0.3.5\] errors during make check [\#194](https://github.com/google/glog/issues/194)
- Allow coredump to be generated upon LOG\(FATAL\) [\#192](https://github.com/google/glog/issues/192)
- Thread ID on macOS [\#182](https://github.com/google/glog/issues/182)
- signalhandler\_unittest tests fails on ppc64le [\#177](https://github.com/google/glog/issues/177)
- --without-gflags is not working [\#175](https://github.com/google/glog/issues/175)
- \(gflags\_reporting.cc.o\): relocation R\_X86\_64\_32 against.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC [\#174](https://github.com/google/glog/issues/174)
- Flag to give users choice to enable or disable time\_pid\_string attaching to the log file name  [\#173](https://github.com/google/glog/issues/173)
- DCHECK\_NOTNULL generates "expression result unused" errors with clang in strict compilation mode [\#172](https://github.com/google/glog/issues/172)
- C4722: destructor never returns potential memory leak [\#171](https://github.com/google/glog/issues/171)
- Logging to the same file from multiple processes [\#170](https://github.com/google/glog/issues/170)
- stacktrace\_libunwind-inl.h: reentrancy check should use a thread-local instead of a global variable [\#160](https://github.com/google/glog/issues/160)
- Support vmodule filter support on non GNU compilers [\#154](https://github.com/google/glog/issues/154)
- can glog write to a specified file name? [\#147](https://github.com/google/glog/issues/147)
- Expose DumpStackTraceToString to application/user [\#144](https://github.com/google/glog/issues/144)
- Adding LOG\_IF\_OR\_EVERY\_N\(\) [\#143](https://github.com/google/glog/issues/143)
- Support initializing logger and sinker by configuration  [\#135](https://github.com/google/glog/issues/135)
- Logging UnitTest failed on x64 VS2015. Reason: Pointer format not consistent [\#134](https://github.com/google/glog/issues/134)
- source/logging\_unittest.cc:64 error : 'GFLAGS\_NAMESPACE' is not not a namespance-name [\#131](https://github.com/google/glog/issues/131)
- Allow glog to be queried as to whether or not InitGoogleLogging has been called. [\#125](https://github.com/google/glog/issues/125)
- Allow a log file to be simply named "foobar.log" with no appended string [\#124](https://github.com/google/glog/issues/124)
- Can I use default FailureSignalHandler\(\) and my custom failure funcion together? [\#121](https://github.com/google/glog/issues/121)
- logging\_fail fail for x64 in VS2013, libglog\_static [\#119](https://github.com/google/glog/issues/119)
- travis env build failure : /bin/bash: aclocal-1.14: command not found [\#117](https://github.com/google/glog/issues/117)
- Allow more than just argv\[0\] in InitGoogleLogging [\#113](https://github.com/google/glog/issues/113)
- Can glog be shutdown totally? [\#111](https://github.com/google/glog/issues/111)
- A memory bug detected by valgrind? [\#109](https://github.com/google/glog/issues/109)
- src/demangle.h:80:27: error: expected initializer before 'Demangle' bool GOOGLE\_GLOG\_DLL\_DECL Demangle\(const char \*mangled, char \*out, int out\_size\); [\#108](https://github.com/google/glog/issues/108)
- glog fails to build on ARM64/AArch64 [\#107](https://github.com/google/glog/issues/107)
- logging\_unittest-logging\_unittest.o ERROR 1 [\#104](https://github.com/google/glog/issues/104)
- FATAL error with pthread\_cancel in multi-thread program [\#102](https://github.com/google/glog/issues/102)
- configure: Hardcoded `am__api_version='1.14'` breaks build on systems with autoconf 1.15 [\#97](https://github.com/google/glog/issues/97)
- ppc64le support for glog [\#89](https://github.com/google/glog/issues/89)
- please remove generated autotools from the git repo [\#86](https://github.com/google/glog/issues/86)
- module based minloglevel [\#66](https://github.com/google/glog/issues/66)
- glog  print wchar\_t? [\#64](https://github.com/google/glog/issues/64)
- Android build is broken [\#59](https://github.com/google/glog/issues/59)
- libglog.pc.in should include libunwind as private dep for static linking case [\#57](https://github.com/google/glog/issues/57)
- demangle\_unittest.sh fails with GCC 5 \(configured --with-default-libstdcxx-abi=new, which is the default\) [\#40](https://github.com/google/glog/issues/40)
- Make the documentation browsable online [\#39](https://github.com/google/glog/issues/39)
- Make error: failed to link with libgflags.a [\#38](https://github.com/google/glog/issues/38)
- Mark LOG\(FATAL\) with \[\[noreturn\]\] [\#28](https://github.com/google/glog/issues/28)
- Logfile with more restrictive permissions control [\#23](https://github.com/google/glog/issues/23)
- Asynchronous/double-buffering support? [\#16](https://github.com/google/glog/issues/16)
- clang34, 35, 36 fails to pass unit tests with C++03 [\#13](https://github.com/google/glog/issues/13)

**Merged pull requests:**

- readme: update CMake source directory option [\#642](https://github.com/google/glog/pull/642) ([husskade](https://github.com/husskade))
- Add Windows builds using GitHub Actions [\#638](https://github.com/google/glog/pull/638) ([NeroBurner](https://github.com/NeroBurner))
- Use generated config.h for Windows. [\#635](https://github.com/google/glog/pull/635) ([drigz](https://github.com/drigz))
- cmake: build shared libs by default [\#632](https://github.com/google/glog/pull/632) ([sergiud](https://github.com/sergiud))
- fixed file extension [\#631](https://github.com/google/glog/pull/631) ([xiaobfly](https://github.com/xiaobfly))
- bazel: use expand\_template instead of genrules [\#628](https://github.com/google/glog/pull/628) ([drigz](https://github.com/drigz))
- cmake: export symbols selectively [\#619](https://github.com/google/glog/pull/619) ([sergiud](https://github.com/sergiud))
- bazel: declare headers in top-level rule [\#615](https://github.com/google/glog/pull/615) ([drigz](https://github.com/drigz))
- Rename BUILD to BUILD.bazel. [\#614](https://github.com/google/glog/pull/614) ([drigz](https://github.com/drigz))
- replaced \_\_CYGWIN32\_\_ and \_\_CYGWIN64\_\_ by \_\_CYGWIN\_\_ [\#611](https://github.com/google/glog/pull/611) ([sergiud](https://github.com/sergiud))
- consolidate readme [\#610](https://github.com/google/glog/pull/610) ([sergiud](https://github.com/sergiud))
- cmake: handle empty unwind version patch component [\#609](https://github.com/google/glog/pull/609) ([sergiud](https://github.com/sergiud))
- Make stl\_logging\_unittest more robust. [\#608](https://github.com/google/glog/pull/608) ([mahiuchun](https://github.com/mahiuchun))
- Fix the symlink creation bug if using bazel [\#600](https://github.com/google/glog/pull/600) ([zoukyle](https://github.com/zoukyle))
- Change counter type to uint64 [\#595](https://github.com/google/glog/pull/595) ([r-barnes](https://github.com/r-barnes))
- src/logging.cc: Fix a typo in comment [\#593](https://github.com/google/glog/pull/593) ([aesophor](https://github.com/aesophor))
- src/logging.cc: Make LogCleaner aware of filename extension \(\#589\) [\#592](https://github.com/google/glog/pull/592) ([aesophor](https://github.com/aesophor))
- remove autoconf support [\#585](https://github.com/google/glog/pull/585) ([sergiud](https://github.com/sergiud))
- Make cmake build on path with spaces. [\#580](https://github.com/google/glog/pull/580) ([Yicong-Huang](https://github.com/Yicong-Huang))
- Added check for if info.dli\_sname is NULL [\#579](https://github.com/google/glog/pull/579) ([arj-fb](https://github.com/arj-fb))
- Add `override` to `LogStreamBuf::overflow()` [\#576](https://github.com/google/glog/pull/576) ([santigl](https://github.com/santigl))
- Add FLAGS\_log\_utc\_time; when 'true' the time will be written in log in UTC, resolves \#571 [\#573](https://github.com/google/glog/pull/573) ([msamoila](https://github.com/msamoila))
- Connect glog to Andorid logging API [\#570](https://github.com/google/glog/pull/570) ([jiuqiant](https://github.com/jiuqiant))
- Output to logcat on Android [\#553](https://github.com/google/glog/pull/553) ([huangqinjin](https://github.com/huangqinjin))
- Make message text null-terminated [\#552](https://github.com/google/glog/pull/552) ([huangqinjin](https://github.com/huangqinjin))
- Replace sprintf\(\) with snprintf\(\) \(\#536\) [\#551](https://github.com/google/glog/pull/551) ([aesophor](https://github.com/aesophor))
- Fix build for Emscripten [\#546](https://github.com/google/glog/pull/546) ([schoppmp](https://github.com/schoppmp))
- OpenBSD/powerpc: clang does not define \_CALL\_\*, use proper ifdef instead [\#545](https://github.com/google/glog/pull/545) ([julianaito](https://github.com/julianaito))
- Use NULL to indicate uninitialized VLOG\_IS\_ON site. [\#542](https://github.com/google/glog/pull/542) ([xulongwu4](https://github.com/xulongwu4))
- Fix unused parameter warning on gcc. [\#540](https://github.com/google/glog/pull/540) ([pwnall](https://github.com/pwnall))
- Prepend the year to each glog line \(\#516\) [\#530](https://github.com/google/glog/pull/530) ([aesophor](https://github.com/aesophor))
- fix bazel build for freebsd [\#526](https://github.com/google/glog/pull/526) ([dfr](https://github.com/dfr))
- Allow CMake user to disable Symbolize functionality [\#523](https://github.com/google/glog/pull/523) ([edbaunton](https://github.com/edbaunton))
- Add target existence checks to Unwind find module [\#518](https://github.com/google/glog/pull/518) ([MichaelDarr](https://github.com/MichaelDarr))
- Add vcpkg installation instructions [\#517](https://github.com/google/glog/pull/517) ([LilyWangL](https://github.com/LilyWangL))
- Explain log levels. [\#515](https://github.com/google/glog/pull/515) ([fmayer](https://github.com/fmayer))
- Use file offsets in traces if object has no symbols [\#513](https://github.com/google/glog/pull/513) ([mspang](https://github.com/mspang))
- Don't call close\(2\) more than once [\#508](https://github.com/google/glog/pull/508) ([xiaosuo](https://github.com/xiaosuo))
- Fix missing deletion of custom Logger [\#503](https://github.com/google/glog/pull/503) ([alexsmac](https://github.com/alexsmac))
- src/logging.cc: encapsulate log cleaner, match logfile with \<base\_filename\_\>\<date\>-\<time\>.\<pid\> [\#502](https://github.com/google/glog/pull/502) ([aesophor](https://github.com/aesophor))
- Address review comments for Bazel/Win32 build [\#499](https://github.com/google/glog/pull/499) ([drigz](https://github.com/drigz))
- Fix race conditions in LOG\_EVERY\_N [\#492](https://github.com/google/glog/pull/492) ([aesophor](https://github.com/aesophor))
- doc: add information about log cleaner [\#491](https://github.com/google/glog/pull/491) ([aesophor](https://github.com/aesophor))
- Added fixed log name support, take 2 [\#489](https://github.com/google/glog/pull/489) ([ezegomez](https://github.com/ezegomez))
- Add windows support for bazel build [\#488](https://github.com/google/glog/pull/488) ([skeptic-monkey](https://github.com/skeptic-monkey))
- src/logging.cc: fix wrong assignment [\#487](https://github.com/google/glog/pull/487) ([Telunsu](https://github.com/Telunsu))
- src/symbolize.cc: do not check for HAVE\_DLFCN\_H for macOS [\#485](https://github.com/google/glog/pull/485) ([ffontaine](https://github.com/ffontaine))
- removed executable flag from .cmake file [\#484](https://github.com/google/glog/pull/484) ([sergiud](https://github.com/sergiud))
- Support pkg-config [\#483](https://github.com/google/glog/pull/483) ([loop0day](https://github.com/loop0day))
- Revert "Added fixed log name support" [\#482](https://github.com/google/glog/pull/482) ([sergiud](https://github.com/sergiud))
- logging: Fix compilation with uClibc++ [\#479](https://github.com/google/glog/pull/479) ([neheb](https://github.com/neheb))
- src/utilities: fix build without pthread [\#477](https://github.com/google/glog/pull/477) ([ffontaine](https://github.com/ffontaine))
- src/symbolize.cc: fix build without dlfcn.h [\#475](https://github.com/google/glog/pull/475) ([ffontaine](https://github.com/ffontaine))
- declare FLAGS\_vmodule [\#467](https://github.com/google/glog/pull/467) ([sukill](https://github.com/sukill))
- I supported clang-cl with BUILD\_SHARED\_LIBS [\#465](https://github.com/google/glog/pull/465) ([durswd](https://github.com/durswd))
- googletest: Switch to nanosleep [\#460](https://github.com/google/glog/pull/460) ([neheb](https://github.com/neheb))
- fix typo: TOOD -\> TODO [\#448](https://github.com/google/glog/pull/448) ([ukai](https://github.com/ukai))
- Don't test on Ubuntu 14.04 [\#446](https://github.com/google/glog/pull/446) ([philwo](https://github.com/philwo))
- Fix symbolize\_unittest for musl builds [\#443](https://github.com/google/glog/pull/443) ([ammubhave](https://github.com/ammubhave))
- Extend the LogSink interface to be able to pass microseconds [\#441](https://github.com/google/glog/pull/441) ([asekretenko](https://github.com/asekretenko))
- Add support for automatic removal of old logs [\#432](https://github.com/google/glog/pull/432) ([aesophor](https://github.com/aesophor))
- Fix logmailer problem for dynamic lib use of glog. [\#400](https://github.com/google/glog/pull/400) ([guoyuhong](https://github.com/guoyuhong))
- Fix warnings [\#370](https://github.com/google/glog/pull/370) ([hemantbits](https://github.com/hemantbits))
- Allow getpwuid\_r to return missing entry. [\#350](https://github.com/google/glog/pull/350) ([TheModMaker](https://github.com/TheModMaker))
- Fix stacktrace on Bazel build. [\#347](https://github.com/google/glog/pull/347) ([nya3jp](https://github.com/nya3jp))
- Fix build for Android API \< 21 [\#312](https://github.com/google/glog/pull/312) ([ruslo](https://github.com/ruslo))
- Use thread local for libunwind GetStackTrace\(\) reentrancy protection [\#161](https://github.com/google/glog/pull/161) ([mpercy](https://github.com/mpercy))
- Respect configured docdir [\#88](https://github.com/google/glog/pull/88) ([kekstee](https://github.com/kekstee))
- Added fixed log name support [\#19](https://github.com/google/glog/pull/19) ([ezegomez](https://github.com/ezegomez))

### CODE REVIEW

**Review by drigz — APPROVED** [review]
Congratulations, Sergiu! What a laundry list!

**Comment by bevinhex** [comment]
conan package is still at 0.4.0, anyone can update it?
