### ISSUE TITLE
Could not compile with custom gflags path

### ISSUE THREAD

**Issue by unemployed-denizen** [google/glog#714]
I tried to compile glog-0.4.0 and I want to install it in a custom directory such as /home/xxxxx/googleopensource
all the source code are stored under /home/xxxxx/googlelibs/glog-0.4.0
gflags has already been installed in /home/xxxxx/googleopensource

now, I run the script
```
target_dir="/home/xxxxx/googleopensource";
cd glog-0.4.0;
mkdir build && cd build;
cmake -DCMAKE_CXX_FLAGS=-std=c++11 -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${target_dir} -Dgflags_DIR=${target_dir}"/lib/cmake/gflags" ..;
make;
make install;
```

I got the following error:
```
[  4%] Building CXX object CMakeFiles/glog.dir/src/demangle.cc.o
In file included from /home/xxxxx/googlelibs/glog-0.4.0/src/utilities.h:84,
                 from /home/xxxxx/googlelibs/glog-0.4.0/src/demangle.cc:38:
/home/xxxxx/googlelibs/glog-0.4.0/build/glog/logging.h:86:10: fatal error: gflags/gflags.h: No such file or directory
   86 | #include <gflags/gflags.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/glog.dir/build.make:63: CMakeFiles/glog.dir/src/demangle.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:928: CMakeFiles/glog.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

It seems that custom path for gflags is not being taken into account when compiling even I added -Dgflags_DIR=${target_dir}"/lib/cmake/gflags"
Can anyone helping me out?

**Comment by sergiud** [comment]
Glog 0.4.0 is outdated. Please use the latest version and report back.

**Comment by unemployed-denizen** [comment]
> Glog 0.4.0 is outdated. Please use the latest version and report back.

I tried v0.5.0 but the same problem still exists with cmake.

Also, I tired
```
./autogen.sh
./configure --prefix=${target_dir}
make;
make install;
```
And it worked with v0.4.0.

**Comment by unemployed-denizen** [comment]
> Did you try using the latest master as well? Otherwise, we need a full reproducer (exact command line, options etc. for compiling gflags & glog with their corresponding versions).

Here is my script, help that helps.
cmake version is 3.16.3
```
target_dir="/rds/homes/x/xxxxxx/googleopensource";

export CXXFLAGS="-std=c++11"

gflags_dir="gflags-2.1.2"
glog_dir="glog-0.5.0"

chmod -R 775 ${gflags_dir};
chmod -R 775 ${glog_dir};
chmod -R 775 ${gtest_dir};


mkdir ${target_dir};
mkdir ${target_dir}"/src";

# gflags always comes first
cd ${gflags_dir};
mkdir build && cd build;
cmake -DCMAKE_CXX_FLAGS=-std=c++11 -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${target_dir} ..;
make;
make install;


# glog depends on gflags
cd ../../${glog_dir};
mkdir build && cd build;
cmake -DCMAKE_CXX_FLAGS=-std=c++11 -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${target_dir} -Dgflags_DIR=${target_dir}"/lib/cmake/gflags" ..;
make;
make install;
```

BTW using ./autogen.sh instead of CMake could solve this problem.

**Comment by sergiud** [comment]
> gflags_dir="gflags-2.1.2"

You could not have tested the latest glog using that script because this gflags version is not supported.

https://github.com/google/glog/blob/2412db315841006e5a4856e64bbb3a274dede0d5/CMakeLists.txt#L79

Apart from that, I cannot reproduce the problem.

> BTW using ./autogen.sh instead of CMake could solve this problem.

This is not a solution because there's no `autogen.sh` anymore.

**Comment by unemployed-denizen** [comment]
Thanks, using gflags==2.2.0 with CMake works!
